# Numpy Exercise  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
#Solution
import numpy as np
np.random.randint(10,29,29)



array([19, 20, 16, 25, 11, 24, 25, 13, 19, 19, 25, 10, 25, 28, 24, 27, 18,
       18, 17, 21, 14, 17, 19, 17, 17, 14, 27, 24, 15])

#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
# Solution
import numpy as np
np.arange(1,50,2)



array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
# Solution
import numpy as np
np.linspace(4,7,27)



array([4.        , 4.11538462, 4.23076923, 4.34615385, 4.46153846,
       4.57692308, 4.69230769, 4.80769231, 4.92307692, 5.03846154,
       5.15384615, 5.26923077, 5.38461538, 5.5       , 5.61538462,
       5.73076923, 5.84615385, 5.96153846, 6.07692308, 6.19230769,
       6.30769231, 6.42307692, 6.53846154, 6.65384615, 6.76923077,
       6.88461538, 7.        ])

#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
# Solution
import numpy as np
np.round(np.random.uniform(1,11,(5,4)),2)



array([[10.78, 10.84,  4.55,  5.03],
       [ 6.46,  9.69,  6.62,  8.15],
       [ 6.72,  3.39,  4.97,  6.85],
       [ 6.8 ,  5.35,  7.25,  1.84],
       [ 8.16,  5.04,  6.07, 10.97]])

#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [5]:
# Solution
import numpy as np
np.random.randint(1,15,(5,5))



array([[12, 12, 10,  7, 13],
       [14,  5, 14, 13,  4],
       [10, 12, 11,  4,  7],
       [10,  4,  9, 12,  8],
       [ 7, 14, 10, 11,  9]])

#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [6]:
# Solution
import numpy as np
lst= [ 0 for i in range(np.random.randint(1,20) ) ]
np.array(lst)



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [7]:
# Solution
w, h = np.random.randint(1,20), np.random.randint(1,20)
Matrix = [[1.0 for x in range(w)] for y in range(h)] 
Matrix



[[1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0]]

#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [8]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(mat)
print(mat.shape)
print(type(mat))
print(mat.dtype)


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
(5, 5)
<class 'numpy.ndarray'>
int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [9]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
mat[len(mat)//2, len(mat)//2]




3

#### 10. Print the all the elements of 3rd row of the matrix

In [10]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
mat[2:3,:]



array([[ 5,  7,  3, 76,  3]])

#### 11. Print the all the elements of 4th columns of the matrix

In [11]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
mat[:,3:4]



array([[34],
       [65],
       [76],
       [54],
       [ 5]])

#### 12. Print the 4 corner pixels of the matrix

In [12]:
# Solution
import numpy as np
a=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
a[::a.shape[0]-1, ::a.shape[1]-1]




array([[ 9, 45],
       [23,  8]])

#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [13]:
# Solution 
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
m1=mat[0:2,2:4]
m2=mat[3:,0:2]
m3=mat[2:,2:]
print(m1)
print(m2)
print(m3)

[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [14]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
a=mat[0:2,2:4]
b=mat[3:,0:2]
c=mat[2:,2:]
print(a.reshape(1,4))
print(b.reshape(1,4))
print(c.reshape(1,9))



[[50 34 34 65]]
[[ 7  8 23 12]]
[[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [15]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
m1=mat[0:2,2:4]
m2=mat[3:,0:2]
print(m1)
print(m2)
print(np.concatenate((m1,m2),axis=1))
print(np.concatenate((m1,m2),axis=0))


[[50 34]
 [34 65]]
[[ 7  8]
 [23 12]]
[[50 34  7  8]
 [34 65 23 12]]
[[50 34]
 [34 65]
 [ 7  8]
 [23 12]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [16]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
m1=mat[0:2,2:4]
m2=mat[3:,0:2]
print(m1+m2)
print(m1-m2)
print(m1*m2)
print(m1/m2)



[[57 42]
 [57 77]]
[[43 26]
 [11 53]]
[[350 272]
 [782 780]]
[[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m3 by removing the first row and last column of m3

In [17]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
m1=mat[0:2,2:4]
m3=mat[2:,2:]
print(m1)
print(m3)
print(m1+m3[1:,:2])




[[50 34]
 [34 65]]
[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]
[[56 88]
 [42 70]]


#### 18. Form the matrix m4 by concatenating (as a new row) the vector [me1, me2] with the matrix m1, where me1 and me2 are the mean values of each column on m1.

In [18]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
m1=mat[0:2,2:4]
m2=m1.mean(0)
print(m1)
print(m2)
m4=np.vstack((m1,m2))
print(m4)


[[50 34]
 [34 65]]
[42.  49.5]
[[50.  34. ]
 [34.  65. ]
 [42.  49.5]]


#### 19. Perform the matrix multiplication between m3 and m4

In [19]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
m1=mat[0:2,2:4]
m2=m1.mean(0)
m3=mat[2:,2:]
m4=np.vstack((m1,m2))
print(m3)
print(m4)
print(np.dot(m3,m4))



[[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]
[[50.  34. ]
 [34.  65. ]
 [42.  49.5]]
[[2860.  5190.5]
 [2388.  4011. ]
 [ 906.   993. ]]


#### 20. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [20]:
# Solution
import numpy as np
mat=np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(mat)
mean=mat.mean(1)
std=mat.std(1)
var=mat.var(1)
print(mean)
print(std)
print(var)
print(max(mean),min(mean))
print(max(std),min(std))
print(max(var),min(var))


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
[32.6 27.6 18.8 16.2 11.2]
[14.65059726 23.41452541 28.63843571 18.91454467  6.30555311]
[214.64 548.24 820.16 357.76  39.76]
32.6 11.2
28.63843571147 6.305553108173779
820.1600000000001 39.760000000000005


#### 21. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [21]:
# Solution 
import numpy as np
runs=np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
print(np.sort(runs.mean(1))[::-1])#Avg

balls=np.array([[50,42,22,65],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])
totalruns=runs.sum(1)
totalballs=balls.sum(1)
print(np.sort((totalruns/totalballs)*100)[::-1])#strike rate

[53.5  51.5  47.25 29.   13.25]
[161.11111111 105.58659218 101.42180095  94.93087558  49.53271028]


#### 22. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [22]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
print('No of students who failed ',len(marks[marks<50]))

print('No of students who passed ',len(marks[marks>=50]))

No of students who failed  3
No of students who passed  7


#### 23. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [23]:
# Solution
import numpy as np
marks = np.array([65,84,47,56,89,98,48,77,80,39])

inipass=len(marks[marks>=50])/len(marks)*100
print(inipass)             

condlist = [(marks>=45)&(marks<=49), (marks>80)&(marks<=95), (marks>96)&(marks<=100)]
choicelist = [marks+5, marks+5,100]

marks = np.select(condlist, choicelist, default=marks)
marks

finpass=len(marks[marks>=50])/len(marks)*100
print(finpass)

#20% increase in pass percentage


70.0
90.0


#### 24. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [32]:

import numpy
import time
   
size = 60000  
   
# declaring lists
list1 = range(1,size)
list2 = range(1,size)
   
# declaring arrays
array1 = numpy.array(range(1,size))  
array2 = numpy.array(range(1,size))  
   
initialTime = time.time()
  
# multiplying  elements of both the lists and stored in another list
resultantList = [(x**2 +8) / y for x, y in zip(list1, list2)]

resultantList
   
# calculating execution time
print("Time taken by Lists to perform multiplication:", 
      (time.time() - initialTime),
      "seconds")
   
initialTime2 = time.time()
  

resultantArray = [(x**2 +8) / y for x, y in zip(array1, array2)]

   
# calculating execution time 
print("Time taken by NumPy Arrays to perform multiplication:",
      (time.time() - initialTime2),
      "seconds")

Time taken by Lists to perform multiplication: 0.020946025848388672 seconds
Time taken by NumPy Arrays to perform multiplication: 0.033358097076416016 seconds


#### 25. Create a Github account and upload your solution with the short write-up on Numpy



https://github.com/monsieurshiva/Numpy-Basic

    
    
NumPy is a library that supports multi-dimensional arrays and matrix functions. It is the fundamental package for scientific computing with Python. 
